import { ThemeProvider } from '@/components/contexts/theme-provider'
import TrpcProvider from '@/components/contexts/trpc-provider'
import { Navbar } from '@/components/other/navbar'
import { Toaster } from '@/components/ui/toaster'
import { cn } from '@/lib/utils'
import { ClerkProvider } from '@clerk/nextjs'
import { dark } from '@clerk/themes'
import type { Metadata } from 'next'
import { Inter as FontSans } from 'next/font/google'
import './globals.css'

export const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function layout({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
      }}
    >
      <TrpcProvider>
        <html lang="en">
          <body
            className={cn(
              'min-h-screen bg-background font-sans antialiased',
              fontSans.variable
            )}
          >
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <div className="flex flex-col-reverse h-screen sm:flex-col">
                <Navbar />
                <main className="px-4 flex flex-col flex-1 overflow-y-scroll p-6">
                  {children}
                </main>
              </div>
            </ThemeProvider>
            <Toaster />
          </body>
        </html>
      </TrpcProvider>
    </ClerkProvider>
  )
}
